name: Build svg2gcode-cli

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Fmt
        run: cargo fmt --check -p svg2gcode-cli
      - name: Clippy
        run: cargo clippy -p svg2gcode-cli -- -D warnings
      - name: Build
        run: cargo build -p svg2gcode-cli
