name: Check svg2gcode-web
on:
  push:
    branches: [main]
  pull_request:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy
      - name: Fmt
        run: cargo fmt --check -p svg2gcode-web
      - name: Clippy
        run: cargo clippy -p svg2gcode-web --target wasm32-unknown-unknown -- -D warnings
      - name: Check
        run: cargo check -p svg2gcode-web --target wasm32-unknown-unknown
